# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9e715eeaf69e224ccc1eb820607c88f772be48d724529b5784fd4cfb899f40aef99dc4cc183b41b8565791927ae1ed5ea88db957bffc61528b7b1195ef462e0

test:
  secret_key_base: 09b00c792956e21c9ddbf9a90a6446dcb14538adeb281a2deaa118a98ce12230de16d4b33c505ce681881c2da08c41395a0963350dafede54e3a6fd3904dc1d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
